FROM nginx:alpine
MAINTAINER hello@heiber.im

ADD nginx-nginx.conf /etc/nginx/nginx.conf

VOLUME ["/var/www/piwigo/galleries", "/var/www/piwigo/upload", "/var/cache/nginx"]

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
