version: "3.6"
services:
  piwigo:
    image: piwigo-docker
    networks:
      - piwigo
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0.18
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - piwigo
    environment:
      MYSQL_USER: "piwigo"
      MYSQL_PASSWORD: "piwigo"
      MYSQL_DATABASE: "piwigo"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

networks:
  piwigo:
