FROM alpine:3.6
MAINTAINER hello@heiber.im

RUN apk --no-cache add php5 php5-fpm php5-gd php5-mysql && \
  mkdir -p /run/php /var/www

ADD fpm-www.conf /etc/php5/php-fpm.conf

VOLUME ["/run/php"]

CMD ["/usr/bin/php-fpm5"]
